# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170303_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Categories'),
        ),
    ]
