# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170303_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderStatus',
            field=models.IntegerField(choices=[(1, 'waiting for delivery'), (2, 'on its way'), (3, 'delivered')], default=1),
        ),
    ]
